# tcsmMuSigInteraction.R
# Interacting functions for running tcsm Python package


#' Convert Catalogs from ICAMS format to tcsm format
#'
#' @param catalog A catalog matrix in ICAMS format. (SNS only!)
#'
#' @return a catalog matrix in tcsm format.
#'
#' @export
ICAMSCatalog2tcsm <- function(catalog) {
  # Read catalog. From matrix-like
  stopifnot(is.data.frame(catalog) | is.matrix(catalog))

  catalog <- t(catalog)
  ICAMSBaseContext <- colnames(catalog)
  baseContextLength <- nchar(ICAMSBaseContext[1])
  Var <- substr(ICAMSBaseContext,baseContextLength,baseContextLength)
  if(baseContextLength == 4){
    Before <- substr(ICAMSBaseContext,1,1)
    Ref <- substr(ICAMSBaseContext,2,2)
    After <- substr(ICAMSBaseContext,3,3)
    tcsmBaseContext <- paste0(Before,"[",Ref,">",Var,"]",After)
  } else if(baseContextLength == 6){
    Before <- substr(ICAMSBaseContext,1,2)
    Ref <- substr(ICAMSBaseContext,3,3)
    After <- substr(ICAMSBaseContext,4,5)
    tcsmBaseContext <- paste0(Before,"[",Ref,">",Var,"]",After)
  }

  colnames(catalog) <- tcsmBaseContext
  return(catalog)
}

#' Read Exposure files in tcsm format.
#'
#' @param exposure Exposure file generated by tcsm.
#' Usually, it is called "W_components.txt".
#'
#' Return ICAMS/SynSigEval formatted exposure matrix.
#'
#' @export
ReadtcsmExposure <- function(exposure){

  exposure <- utils::read.table(
    file = exposure, header = T,
    sep = "\t", as.is = T)
  return(exposure)
}

#' Read Catalog files or matrices in tcsm format.
#'
#' @param cat Input catalog, can be a tab-delimited text
#' file in tcsm format, or a matrix/data.frame object.
#'
#' @param region Catalog region. Can be a specific genomic
#' or exonic region, or "unknown".
#' Default: "unknown"
#'
#' @param catalog.type Is the catalog a signature catalog,
#' or a spectrum catalog?
#' Default: "counts.signature"
#'
#' @return a catalog matrix in ICAMS format.
#'
#' @export
tcsmCatalog2ICAMS <- function(cat,
                            region = "unknown",
                            catalog.type = "counts.signature"){

  stopifnot(is.character(cat) | is.data.frame(cat) | is.matrix(cat))
  if(class(cat) == "character") {
    catMatrix <- read.table(file = cat, header = T,
                            sep = "\t", as.is = T,
                            check.names = FALSE)
  } else {
    catMatrix <- cat
  }

  rownames(catMatrix) <- catMatrix[,1]
  catMatrix <- t(catMatrix[,-1])
  tcsmBaseContext <- rownames(catMatrix)
  baseContextLength <- nchar(tcsmBaseContext[1])
  if(baseContextLength == 7){ ## trinucleotide base context
    Before <- substr(tcsmBaseContext,1,1)
    Ref <- substr(tcsmBaseContext,3,3)
    Var <- substr(tcsmBaseContext,5,5)
    After <- substr(tcsmBaseContext,7,7)

  }else if(baseContextLength == 9){ ## pendanucleotide base context
    Before <- substr(tcsmBaseContext,1,2)
    Ref <- substr(tcsmBaseContext,4,4)
    Var <- substr(tcsmBaseContext,6,6)
    After <- substr(tcsmBaseContext,8,9)
  }
  catMatrix <- ICAMS::as.catalog(object = catMatrix,
                                 region = region,
                                 catalog.type = catalog.type)
  return(catMatrix)
}

#' Prepare input file for tcsm from a
#' tcsm formatted catalog file.
#'
#' @param catalog a catalog in ICAMS format. It can be
#' a .csv file, or a matrix or data.frame.
#' Usually, it refers to \code{"ground.truth.syn.catalog.csv"}.
#'
#' @param out.dir Directory that will be created for the output;
#' abort if it already exists. Usually, the \code{out.dir} will
#' be a \code{tcsm.results} folder directly under the
#' folder storing \code{catalog}.
#'
#' @param overwrite If TRUE, overwrite existing output
#'
#' @return \code{invisible(catMatrix)},
#' original catalog in tcsm format
#'
#' @details Creates folder named \code{tcsm.results} containing catalogs
#' in tcsm-formatted catalogs: Rows are signatures;
#' the first column is the name of the mutation type, while the remaining
#' columns are samples (tumors).
#' These tcsm-formated catalogs will the input when running tcsm program
#' later on Python platform.
#'
#' @export
#'
#' @importFrom utils capture.output
CreatetcsmOutput <-
  function(catalog,
           out.dir = paste0(dirname(catalog),"/ExtrAttr/tcsm.results"),
           overwrite = FALSE) {

  ## If catalog is a string of file path
  if(is.character(catalog)){
    ## Read in catalog matrix using ICAMS::ReadCatalog.
    catMatrix <- ICAMS::ReadCatalog(catalog, strict = FALSE)
    ## Convert catalog to tcsm format
    catMatrix <- ICAMSCatalog2tcsm(catMatrix)
    ## Fetch the name of catalog file without extension
    oldFileName <- tools::file_path_sans_ext(basename(catalog))
  } else if(is.data.frame(catalog) | is.matrix(catalog)) {
    ## Assume `catalog` is a legal ICAMS catalog object.
    ## Convert catalog to tcsm format
    catMatrix <- ICAMSCatalog2tcsm(catalog)
    ## Fetch the name of catalog file
    oldFileName <- "ground.truth.syn.catalog"
  }

  ## Create out.dir
  dir.create(out.dir,recursive = T)

  ## Dump catMatrix into out.dir
  newFileName <- paste0(out.dir,"/",oldFileName,".tsv")
  utils::write.table(
    catMatrix, file = newFileName,
    sep = "\t")

  ## Return catMatrix, invisibly.
  invisible(catMatrix)
}

