## Specify default options
options(stringsAsFactors = F)

## Specify dataset names
slopes <- c(0.1,0.5,1,2,10)
Rsqs <- c(0.1,0.2,0.3,0.6)
datasetNames <- character(0)

for(slope in slopes){
  for(Rsq in Rsqs){
    datasetNames <- c(datasetNames,
                      paste0("S.",slope,".Rsq.",Rsq))
  }
}
## Specify tool Names
# R-based tools which can do both extraction and attribution,
# excluding SignatureAnalyzer (due to special folder structure)
# and maftools (its seed is hard-coded)
RBasedExtrAttrToolNames <- c("signeR","hdp","hdp.clean","sigfit.nmf","sigfit.emu")
# Python or other language based tools.
# excluding maftools (seed is fixed) and EMu (cannot designate seed)
otherExtrAttrToolNames <- c("MultiModalMuSig","SignatureAnalyzer","sigproextractor")
# Tools can only do attribution
attrToolNames <-
  c("decompTumor2Sig","deconstructSigs","mSigAct",
    "MutationalPatterns","mutSignatures",
    "SignatureEstimation.QP","SignatureEstimation.SA",
    "YAPSA","sigfit.nmf","sigfit.emu","sigproextractor")


## Specify seeds used in analysis.
## Specify 20 seeds used in software running
seedsInUse <- c(1, 691, 1999, 3511, 8009,
                9902, 10163, 10509, 14476, 20897,
                27847, 34637, 49081, 75679, 103333,
                145879, 200437, 310111, 528401, 1076753)


##
for(datasetName in datasetNames){

  for(toolName in c(RBasedExtrAttrToolNames,otherExtrAttrToolNames)){
    ## Clean up all SummarizeMultiRuns() Output.
    oneToolFolder <- paste0(datasetName,"/sp.sp/ExtrAttr/",toolName,".results/")
    filesToBeDeleted <- list.files(path = oneToolFolder,full.names = T)
    ## Don't delete directories!
    ## Just delete top-level files generated by SummarizeMultiRuns
    unlink(filesToBeDeleted,recursive = F)
  }

  ## Clean up all SummarizeMultiToolsOneDataset() output.
  for(thirdLevelDir in c("ExtrAttr","Attr")){
    multiToolFolder <- paste0(datasetName,"/sp.sp/",thirdLevelDir,"/")
    filesToBeDeleted <- list.files(path = multiToolFolder,full.names = T)
    unlink(filesToBeDeleted,recursive = F)
  }

}



