## Specify default options
options(stringsAsFactors = F)

## Specify dataset names
slopes <- c(0.1,0.5,1,2,10)
Rsqs <- c(0.1,0.2,0.3,0.6)
datasetNames <- character(0)

for(slope in slopes){
  for(Rsq in Rsqs){
    datasetNames <- c(datasetNames,
                      paste0("S.",slope,".Rsq.",Rsq))
  }
}
## Specify tool Names
# R-based tools which can do both extraction and attribution,
# excluding SignatureAnalyzer (due to special folder structure)
# and maftools (its seed is hard-coded)
RBasedExtrAttrToolNames <- c("signeR","hdp","hdp.clean","sigfit.nmf","sigfit.emu")
# Python or other language based tools.
# excluding maftools (seed is fixed) and EMu (cannot designate seed)
otherExtrAttrToolNames <-
  c("MultiModalMuSig","SignatureAnalyzer",
    "sigproextractor","helmsman")
# Tools can only do attribution
attrToolNames <-
  c("decompTumor2Sig","deconstructSigs","mSigAct",
    "MutationalPatterns","mutSignatures",
    "SignatureEstimation.QP","SignatureEstimation.SA",
    "YAPSA","sigfit.nmf","sigfit.emu","sigproextractor")


## Specify seeds used in analysis.
## Specify 20 seeds used in software running
seedsInUse <- c(1, 691, 1999, 3511, 8009,
                9902, 10163, 10509, 14476, 20897,
                27847, 34637, 49081, 75679, 103333,
                145879, 200437, 310111, 528401, 1076753)

## Clean up all SummarizeSigOneSubdir(), SummarizeSigOneSASubdir()
## SummarizeSigOnehelmsmanSubdir(), SummarizeSigOneSPSubdir() output.
## Note: the folder structure of EMu and maftools are different from
## the structure of other packages.
## This is because EMu cannot specify seeds; while maftools have a fixed
## seed (123456).
## Part I: Run Summarize functions in SynSigEval
for(datasetName in datasetNames){
  for(seedInUse in seedsInUse){
    ## Delete summary of R-based and non-R based Extraction and attribution tools.
    for(extrAttrToolName in c(RBasedExtrAttrToolNames,otherExtrAttrToolNames)){
      unlink(
        paste0(datasetName,"/sp.sp/ExtrAttr/",extrAttrToolName,
               ".results/seed.",seedInUse,"/summary/"),
        recursive = FALSE)
    }
    ## Delete summary of R-based attribution-only tools.
    for(attrToolName in attrToolNames){
      unlink(
        paste0(datasetName,"/sp.sp/Attr/",extrAttrToolName,
               ".results/seed.",seedInUse,"/summary/"),
        recursive = FALSE)
    }
  }
  ## Delete summary of maftools
    unlink(paste0(datasetName,
                  "/sp.sp/ExtrAttr/maftools.results/seed.123456","/summary/"),
    recursive = FALSE)
  ## Summarize EMu
  for(nrun in 1:20){
    unlink(
      paste0(datasetName,"/sp.sp/ExtrAttr/","EMu",
                       ".results/run.",nrun,"/summary/"),
      recursive = T)
  }
}


## Clean up all SummarizeMultiRuns() Output, all SummarizeMultiToolsOneDataset() output
## Note: for these outputs, the folder structure of EMu and maftools are the same
## as other tools.
otherExtrAttrToolNames <- c("MultiModalMuSig","SignatureAnalyzer","sigproextractor",
                            "EMu","maftools")

for(datasetName in datasetNames){

  for(toolName in c(RBasedExtrAttrToolNames,otherExtrAttrToolNames)){
    ## Clean up all SummarizeMultiRuns() Output.
    oneToolFolder <- paste0(datasetName,"/sp.sp/ExtrAttr/",toolName,".results/")
    filesToBeDeleted <- list.files(path = oneToolFolder,full.names = T)
    ## Don't delete directories!
    ## Just delete top-level files generated by SummarizeMultiRuns
    unlink(filesToBeDeleted,recursive = F)
  }

  ## Clean up all SummarizeMultiToolsOneDataset() output.
  for(thirdLevelDir in c("ExtrAttr","Attr")){
    multiToolFolder <- paste0(datasetName,"/sp.sp/",thirdLevelDir,"/")
    filesToBeDeleted <- list.files(path = multiToolFolder,full.names = T)
    unlink(filesToBeDeleted,recursive = F)
  }

}



