# EMuMuSigInteraction.R
# Interacting functions for running EMu Python package


#' Convert Catalogs from ICAMS format to EMu format
#'
#' @param catalog A catalog matrix in ICAMS format. (SNS only!)
#'
#' @return a catalog matrix in EMu format.
#'
#' @export
ICAMSCatalog2EMu <- function(catalog) {
  # Read catalog. From matrix-like
  stopifnot(is.data.frame(catalog) | is.matrix(catalog))
  return(catalog)
}

#' Read Exposure files in EMu format.
#'
#' @param exposure Exposure file generated by EMu.
#' Usually, it is called "W_components.txt".
#'
#' Return ICAMS/SynSigEval formatted exposure matrix.
#'
#' @export
ReadEMuExposure <- function(exposure){

  exposure <- utils::read.table(
    file = exposure, header = T,
    sep = "\t", as.is = T)
  return(exposure)
}

#' Read Catalog files or matrices in EMu format.
#'
#' @param cat Input catalog, can be a tab-delimited text
#' file in EMu format, or a matrix/data.frame object.
#'
#' @param region Catalog region. Can be a specific genomic
#' or exonic region, or "unknown".
#' Default: "unknown"
#'
#' @param catalog.type Is the catalog a signature catalog,
#' or a spectrum catalog?
#' Default: "counts.signature"
#'
#' @return a catalog matrix in ICAMS format.
#'
#' @export
EMuCatalog2ICAMS <- function(cat,
                            region = "unknown",
                            catalog.type = "counts.signature"){

  stopifnot(is.character(cat) | is.data.frame(cat) | is.matrix(cat))
  if(class(cat) == "character") {
    catMatrix <- utils::read.table(
      file = cat, header = T,
      sep = "\t", as.is = T,
      check.names = FALSE)
  } else {
    catMatrix <- cat
  }
  catMatrix <- ICAMS::as.catalog(object = catMatrix,
                                 region = region,
                                 catalog.type = catalog.type)
  return(catMatrix)
}

#' Prepare input file for EMu from a
#' EMu formatted catalog file.
#'
#' @param catalog a catalog in ICAMS format. It can be
#' a .csv file, or a matrix or data.frame.
#' Usually, it refers to \code{"ground.truth.syn.catalog.csv"}.
#'
#' @param read.catalog.function Function taking a file path as
#' its only argument and returning a catalog as a numeric matrix.
#'
#' @param out.dir Directory that will be created for the output;
#' abort if it already exists. Usually, the \code{out.dir} will
#' be a \code{EMu.results} folder directly under the
#' folder storing \code{catalog}.
#'
#' @param overwrite If TRUE, overwrite existing output
#'
#' @return \code{invisible(catMatrix)},
#' original catalog in EMu format
#'
#' @details Creates folder named \code{EMu.results} containing catalogs
#' in EMu-formatted catalogs: Rows are signatures;
#' the first column is the name of the mutation type, while the remaining
#' columns are samples (tumors).
#' These EMu-formated catalogs will the input when running EMu program
#' later on Python platform.
#'
#' @export
#'
#' @importFrom utils capture.output
CreateEMuOutput <-
  function(catalog,
           read.catalog.function = NULL,
           out.dir = paste0(dirname(catalog),"/ExtrAttr/EMu.results"),
           overwrite = FALSE) {

  ## If catalog is a string of file path
  if(is.character(catalog)){
    ## Read in catalog matrix using read.catalog.function.
    catMatrix <- read.catalog.function(catalog, strict = FALSE)
    ## Convert catalog to EMu format
    catMatrix <- ICAMSCatalog2EMu(catMatrix)
    ## Fetch the name of catalog file without extension
    oldFileName <- tools::file_path_sans_ext(basename(catalog))
  } else if(is.data.frame(catalog) | is.matrix(catalog)) {
    ## Assume `catalog` is a legal ICAMS catalog object.
    ## Convert catalog to EMu format
    catMatrix <- ICAMSCatalog2EMu(catalog)
    ## Fetch the name of catalog file
    oldFileName <- "ground.truth.syn.catalog"
  }

  ## Create out.dir
  dir.create(out.dir,recursive = T)

  ## Dump catMatrix into out.dir
  newFileName <- paste0(out.dir,"/",oldFileName,".tsv")
  utils::write.table(
    catMatrix, file = newFileName,
    sep = "\t")

  ## Return catMatrix, invisibly.
  invisible(catMatrix)
}

